---
services:
  db:
    image: ankane/pgvector
    ports:
     - 5432:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vectordb
      - POSTGRES_PASSWORD=vectordb
      - POSTGRES_HOST_AUTH_METHOD=trust

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    # https://github.com/ollama/ollama?tab=readme-ov-file#model-library
    tty: true
    volumes:
      - ./.ollama:/root/.ollama

  # gpu enabled
  # ollama:
  #   image: ollama/ollama:roc
  #   ports:
  #     - 11434:11434
  #   restart: unless-stopped
  #   tty: true
  #   volumes:
  #     - ./.ollama:/root/.ollama
  #   devices:
  #     - /dev/kfd
  #     - /dev/dri
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: ["gpu"]

  webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    volumes:
      - ./.webui:/app/backend/data
    ports:
      - 8080:8080
    environment:
      - '/ollama/api=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    depends_on:
      - ollama

  sciphi:
    build: .
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - CONFIDENTAI_API_KEY=${CONFIDENTAI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=vectordb
      - POSTGRES_PASSWORD=vectordb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=vectordb
      - CONFIG_PATH=config.json
    volumes:
      - ./.ollama:/opt/ollama
    depends_on:
      - db
      - ollama
